name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macOs]
        python-version: [3.9, pypy3]

    steps:
    - uses: actions/checkout@v2

    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.1.4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: tox -e py
